version: "3"
services:
  mongo:
      image: mongo
      restart: always
      tty: true
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
        MONGO_INITDB_DATABASE: admin
      ports:
        - ${MONGODB_PORT}:27017
      volumes:
        - .docker/mongodb:/var/micro-data/mongodb/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongo:${MONGODB_PORT}